Repository kebluis/eod-report-pomodoro-client, pull requests merged in 2023-05, with the labels that each got.

#8 pause functionality and notification fix
  src/components/CountdownComponent.js
Labels: enhancement

#7 Revised Break Service including Short and Long
  assets/meditatingWork.json
  assets/seaWalk.json
  assets/typing.json
  src/components/CountdownComponent.js
  src/components/ServiceNavigatorComponent.js
  src/components/TaskComponent.js
  src/constants/global.js
  src/model/serviceNavigation.js
  src/screens/DashboardScreen.js
  src/store/ServiceContext/index.js
  src/store/ServiceContext/reducer.js
Labels: enhancement

#4 Created settings page and added navigation header
  package.json
  src/components/EmailRow.js
  src/components/navigation/Navigations.js
  src/css/global.js
  src/screens/DashboardScreen.js
  src/screens/Settings.js
Labels: enhancement, help wanted, good first issue

#11 Login Navigation Fix
  src/axios/api.js
  src/components/ServiceNavigatorComponent.js
  src/components/TasklistComponent.js
  src/fixtures/serviceNavigation.js
  src/model/DashboardModel.js
  src/screens/LoginScreen.js
  src/store/AuthContext/index.js
  src/store/AuthContext/reducer.js
Labels: enhancement

#12 ID Token Fix
  src/screens/LoginScreen.js
Labels: bug
